

[workspace]
members = [ 
  "libchess",
  "perft",
  "positioning"
]

resolver = "2"

[profile.release]
opt-level = 3
overflow-checks=false
codegen-units=1
lto="fat"
# strip = "debuginfo"

[profile.dev]
opt-level = 1


